### ISSUE TITLE
InvokeGlobalListeners is not called when RegisterStore is used

### ISSUE THREAD

**Issue by rotty3000** [microsoft/redux-micro-frontend#16]
**Describe the bug**
InvokeGlobalListeners is not called when RegisterStore is used

**To Reproduce**
1. Register a manually created store using GlobalStore.RegisterStore
2. subscribe to global state using `globalStore.SubscribeToGlobalState(..)`
3. trigger any store actions
4. global listeners are not triggered

**Expected behavior**
global listeners are called for state changes in any store.

**Comment by patrickCode** [comment]
I will investigate a bit more on this and get back on this issue. For clarification when you say you are triggering any store actions, are you triggering the action on the store directly or via the Global Store methods?

**Comment by rotty3000** [comment]
so for stores which are `RegisterStore`'d rather than `CreateStore`'d.

You can see that in CreateStore you've called [`appStore.subscribe(this.InvokeGlobalListeners.bind(this));`](https://github.com/microsoft/redux-micro-frontend/blob/81a399e97498737942dd6b3528ca54ba24079975/src/global.store.ts#L71)

but in RegisterStore you haven't.

In fact it looks almost like if you move line 71 to bellow line 98 you'd cover both scenarios.

**Comment by patrickCode** [comment]
Actually I was thinking of the same thing. I will fix and release a new version on Monday. Does that work for you?

**Comment by patrickCode** [comment]
Sorry I got busy with some critical work. Thanks for the PR @rotty3000

**Comment by rotty3000** [comment]
No problem at all! Thanks for merging 😊

**Comment by patrickCode** [comment]
Version 1.1.0 was release which will have the changes
