### ISSUE TITLE
queued subscribe callbacks for missing stores

### ISSUE THREAD

**Issue by rotty3000** [microsoft/redux-micro-frontend#17]
**Is your feature request related to a problem? Please describe.**
I get an error when subscribing to a missing store.

**Describe the solution you'd like**
Instead of getting an error when subscribing to a missing store, I'd rather the callback be queued up for the possible eventual arrival of the store (maybe never). Meanwhile, the unsubscribe would pull the callback out of the queue if no store ever arrived.
Of course if the store did eventually arrive the queued callback should be pulled out of the queue, applied to the store.

**Describe alternatives you've considered**
Not sure of any alternatives.

**Comment by patrickCode** [comment]
This is a really interesting use case! Let me think of this this a little bit and get back to you with a solution.

**Comment by rotty3000** [comment]
Maybe this is just a new subscribe method leaving the other with current behavior?

**Comment by patrickCode** [comment]
This feature has been added in v1.2.0
