### ISSUE TITLE
Doesn't work with Jest

### ISSUE THREAD

**Issue by amanda-natallie** [microsoft/redux-micro-frontend#8]
I'm trying to test my application using Jest lib and getting the following error: 

![image](https://user-images.githubusercontent.com/44005675/106605209-64989b80-653f-11eb-93a6-94767da1916d.png)

I've tryed common solutions like babel-jest and other configurations mentioned on docs. but have no result. Can you check?

**Comment by patrickCode** [comment]
Is it possible to send me a link to your project. I would like to check you configurations for jest.

**Comment by dmesa89** [comment]
Hi, how was this issue solved?

**Comment by cyberduck1** [comment]
Experiencing the same problem, any suggestion on how to solve this?

**Comment by manuelbasanta** [comment]
How was this solved?
