### ISSUE TITLE
Need control on the format of the event logs this library is adding

### ISSUE THREAD

**Issue by hkgupta** [microsoft/redux-micro-frontend#9]
**Is your feature request related to a problem? Please describe.**
The event logs in the logger is not customizable for the consumer application. 

**Describe the solution you'd like**
Currently we have the option to pass our own logger instance but it doesn't give me control to pass what should be the source or the even name for same.

**Comment by patrickCode** [comment]
Clients need to pass the actual logger implementation. The source and event prefix can be taken care at the client end in the actual logger implementation.
To comply with general telemetry standards the event name (during Store Registration) will be changed.
